version: '3.8'

volumes:
  pg_data:

services:
  db:
    image: postgres:17
    env_file: ../.env
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ../.env
    depends_on:
      - db
    ports:
      - 8000:8000
