# Generated by Django 5.1.4 on 2025-01-06 19:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("breed", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "age",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(30),
                        ]
                    ),
                ),
                ("gender", models.CharField(max_length=150)),
                ("color", models.CharField(max_length=200)),
                ("favorite_food", models.CharField(max_length=250)),
                ("favorite_toy", models.CharField(max_length=250)),
                (
                    "breed",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="breed.breed"),
                ),
            ],
        ),
    ]
